name: 'CodeScribe AI'
description: 'An action that automatically creates documentation for code files in merged PRs using AI'
author: 'yybmion'

inputs:
  github-token:
    description: 'GitHub token used for API access'
    required: true
    default: ${{ github.token }}

  ai-provider:
    description: 'AI provider (openai, anthropic, google)'
    required: false
    default: 'google'

  ai-model:
    description: 'AI model to use (gpt-4, claude-3-opus, gemini-2.0-flash, etc.)'
    required: false
    default: 'gemini-2.0-flash'

  ai-api-key:
    description: 'API key for the chosen AI provider'
    required: true

  language:
    description: 'Documentation language (ko, en)'
    required: false
    default: 'en'

runs:
  using: 'node20'
  main: 'dist/main.js'

branding:
  icon: 'book-open'
  color: 'black'
